In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
data_import = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/teleCust1000t.csv')
data_import

region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9    64.0   4       5     0.0   
1         3      11   33        1        7   136.0   5       5     0.0   
2         3      68   52        1       24   116.0   1      29     0.0   
3         2      33   33        0       12    33.0   2       0     0.0   
4         2      23   30        1        9    30.0   1       2     0.0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0    27.0   3       0     0.0   
996       1       7   34        0        2    22.0   5       5     0.0   
997       3      67   59        0       40   944.0   5      33     0.0   
998       3      70   49        0       18    87.0   2      22     0.0   
999       3      50   36        1        7    39.0   3       3     0.0   

     gender  reside  custcat  
0         0       2        1  
1         0       6        4  
2         1       2        3  
3         1       1        1  
4         0       4        3  
..      ...     ...      ...  
995       1       3        1  
996       1       1        1  
997       1       1        4  
998       1       1        3  
999       1       3        2  

[1000 rows x 12 columns]

In [4]:
data_import.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [10]:
x = data_import[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside']].values
x[:5]

array([[  2.,  13.,  44.,   1.,   9.,  64.,   4.,   5.,   0.,   0.,   2.],
       [  3.,  11.,  33.,   1.,   7., 136.,   5.,   5.,   0.,   0.,   6.],
       [  3.,  68.,  52.,   1.,  24., 116.,   1.,  29.,   0.,   1.,   2.],
       [  2.,  33.,  33.,   0.,  12.,  33.,   2.,   0.,   0.,   1.,   1.],
       [  2.,  23.,  30.,   1.,   9.,  30.,   1.,   2.,   0.,   0.,   4.]])

In [31]:
y = data_import['custcat'].values
y[:5]

array([1, 4, 3, 1, 3], dtype=int64)

In [20]:
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float))
x[:5]

array([[-0.02696767, -1.055125  ,  0.18450456,  1.0100505 , -0.25303431,
        -0.12650641,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817,
        -0.23065004],
       [ 1.19883553, -1.14880563, -0.69181243,  1.0100505 , -0.4514148 ,
         0.54644972,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817,
         2.55666158],
       [ 1.19883553,  1.52109247,  0.82182601,  1.0100505 ,  1.23481934,
         0.35951747, -1.36767088,  1.78752803, -0.22207644,  0.96655883,
        -0.23065004],
       [-0.02696767, -0.11831864, -0.69181243, -0.9900495 ,  0.04453642,
        -0.41625141, -0.54919639, -1.09029981, -0.22207644,  0.96655883,
        -0.92747794],
       [-0.02696767, -0.58672182, -0.93080797,  1.0100505 , -0.25303431,
        -0.44429125, -1.36767088, -0.89182893, -0.22207644, -1.03459817,
         1.16300577]])

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 3)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 11), (200, 11), (800,), (200,))

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
k = 6
KNN = KNeighborsClassifier(n_neighbors = k)
KNN.fit(x_train, y_train)
y_ = KNN.predict(x_test)
y_

array([1, 4, 3, 3, 1, 2, 3, 2, 1, 1, 1, 4, 3, 1, 2, 3, 3, 3, 3, 2, 4, 1,
       2, 3, 1, 1, 4, 1, 2, 1, 1, 2, 4, 4, 3, 1, 2, 1, 3, 1, 1, 1, 2, 2,
       2, 3, 2, 1, 1, 4, 4, 2, 1, 1, 2, 1, 4, 3, 1, 3, 1, 1, 3, 1, 1, 4,
       2, 1, 1, 1, 4, 1, 1, 2, 3, 3, 1, 2, 2, 4, 4, 3, 3, 3, 1, 2, 4, 1,
       2, 3, 3, 1, 3, 3, 4, 1, 3, 4, 2, 1, 2, 3, 3, 2, 3, 4, 4, 1, 2, 2,
       1, 1, 2, 1, 4, 1, 1, 1, 4, 1, 4, 2, 2, 3, 2, 3, 4, 2, 1, 1, 1, 1,
       4, 1, 1, 2, 1, 4, 1, 1, 2, 1, 1, 2, 2, 1, 3, 1, 1, 2, 2, 2, 3, 3,
       3, 1, 1, 1, 3, 1, 3, 2, 2, 1, 3, 2, 1, 2, 3, 1, 1, 3, 2, 3, 3, 4,
       3, 3, 1, 2, 4, 1, 1, 1, 2, 3, 3, 1, 3, 3, 4, 1, 1, 3, 3, 2, 1, 1,
       3, 4], dtype=int64)

In [62]:
from sklearn import metrics
metrics.accuracy_score(y_train, KNN.predict(x_train)), metrics.accuracy_score(y_test, y_)

(0.5275, 0.325)

In [104]:
K = 10
accuracy = np.zeros(9)

for n in range(1,K):
    KNN1 = KNeighborsClassifier(n_neighbors = n)
    KNN1.fit(x_train, y_train)
    y_ = KNN1.predict(x_test)
    accuracy[n-1] = metrics.accuracy_score(y_test, y_)
    #print('accuracy : %.2f' % metrics.accuracy_score(y_test, y_))
    
print(accuracy)
max_accuracy_loc_in_K = np.where(accuracy == accuracy.max())
k_loc = max_accuracy_loc_in_K[0][0]+1
print('The best accuracy is ', accuracy.max(), 'with k =',k_loc)

[0.32  0.325 0.335 0.295 0.31  0.325 0.31  0.325 0.345]
The best accuracy is  0.345 with k = 9
